# Generated by Django 5.2.13 on 2026-04-10 18:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('youtube', 'YouTube'), ('file', 'Archivo'), ('text', 'Texto'), ('gmetrix', 'GMetrix')], max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('raw_text', models.TextField(blank=True)),
                ('translated_text', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('key_points', models.JSONField(default=list)),
                ('language', models.CharField(blank=True, default='es', max_length=10)),
                ('duration_secs', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('done', 'Completada'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_msg', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
